### ISSUE TITLE
Rajouter l'IBAN dans le paiement par virement bancaire

### ISSUE THREAD

**Issue by Kaeligmo** [WigwamCoworking/site#12]
![image](https://user-images.githubusercontent.com/48795832/55538884-b52edb80-56bf-11e9-90eb-8069a1113924.png)

**Comment by corsonr** [comment]
quel est l'IBAN à ajouter ?

**Comment by Kaeligmo** [comment]
*removed*

**Comment by corsonr** [comment]
Sur slack, @o-Chamie-o :

>Pour l'IBAN on avait choisi de ne pas rendre publique il me semble, rapport au hack du fablab
En gros il avait leur RIB public sur leur site, et il ont subit une usurpation d'idéntité
avec prélevement sur leur compte ça tappai dans les millers d'euro je sais plus combien... après on a des assurances, c'est juste chiant si ça nous arrive

**Comment by JMPivette** [comment]
L'IBAN ne sera pas en public sur le site mais est épinglé dans Slack pour que tous les membres puissent y avoir accès

**Comment by corsonr** [comment]
IBAN ajouté, pas visible sur page commande, envoyé par email.
