### ISSUE TITLE
Ajouter l'option de paiement Stripe

### ISSUE THREAD

**Issue by JMPivette** [WigwamCoworking/site#16]
Nous avons créé un compte Stripe pour remplacer le paiement Paypal.
Quand j'essaie d'ajouter une extension "Stripe" sur woocommerce, on me demande un compte woocommerce et a priori wigwam@coworking-lannion.org n'est pas un utilisateur.

Est-ce que tu peux ajouter l'extension Stripe? (ou me montrer comment faire?)

**Comment by o-Chamie-o** [comment]
done
