### ISSUE TITLE
rendre visible le champ "mode de paiement" sur la présentation liste commande 

### ISSUE THREAD

**Issue by sophiemarech** [WigwamCoworking/site#3]
Je voudrais voir apparaître la mention du mode de paiement sur la liste des commandes (champ visible - par ex entre "Etat" et "Total")

![image](https://user-images.githubusercontent.com/47322081/52208984-c0fa4f00-2882-11e9-8ccf-386b40cfbf5b.png)

**Comment by corsonr** [comment]
Done!

![](https://d.pr/free/i/2y9hJt+)
