### ISSUE TITLE
Ajouter le téléchargement des factures

### ISSUE THREAD

**Issue by Kaeligmo** [WigwamCoworking/site#5]

**Comment by JMPivette** [comment]
Il manque le téléchargement des factures mais aussi l'envoi de facture en pièce jointe lors de la validation

**Comment by corsonr** [comment]
WooCommerce n'envoit pas de pièce jointe par défaut, le plugin **PDF Invoices** résoudra ces deux points.

**Comment by corsonr** [comment]
Extension [PDF Invoices](https://www.woocommerce.com/products/pdf-invoices/?aff=10486&cid=1131038) uploadée, activée et configurée.
