### ISSUE TITLE
Tous les liens de la page d'accueil ramènent sur coworking-lannion.org/plan/

### ISSUE THREAD

**Issue by Kaeligmo** [WigwamCoworking/site#7]

**Comment by corsonr** [comment]
quels liens  exactement ? Où devraient-ils pointer ?

**Comment by afriqs** [comment]
§ Un coworking participatif : lien *En savoir+*

§ Le wingwam, association loi 1901 : lien *L'association*

En fait il n'y a pas de description de *l'offre*, juste la possibilité de choisir son plan :thinking:

**Comment by o-Chamie-o** [comment]
fix
